#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x keyword_hash_builder`
puts `gem build keyword_hash_builder.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
